name: Sync with Upstream and Preserve Custom Changes

on:
  schedule:
    - cron: '0 0 * * 1'  # 毎週月曜日の午前0時に実行
  workflow_dispatch:  # 手動実行用

jobs:
  sync-and-preserve:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Sync with upstream
        run: |
          git remote add upstream https://github.com/nvim-lua/kickstart.nvim.git
          git fetch upstream
          git checkout main
          git merge upstream/main --no-commit

      - name: Check for conflicts
        id: check_conflicts
        run: |
          if git diff --name-only --diff-filter=U | grep . > /dev/null; then
            echo "::set-output name=has_conflicts::true"
          else
            echo "::set-output name=has_conflicts::false"
          fi

      - name: Push changes if no conflicts
        if: steps.check_conflicts.outputs.has_conflicts == 'false'
        run: |
          git commit -m "Merge upstream changes"
          git push origin main

      - name: Create Pull Request if conflicts
        if: steps.check_conflicts.outputs.has_conflicts == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          branch: upstream-sync
          title: 'Resolve conflicts with upstream'
          body: 'This PR was created to resolve conflicts with the upstream repository. Please resolve the conflicts manually.'
          base: main