name: Sync with Upstream and Preserve Custom Changes

on:
  schedule:
    - cron: '0 0 * * 1'  # 毎週月曜日の午前0時に実行
  workflow_dispatch:  # 手動実行用

jobs:
  sync-and-preserve:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # v4 is the latest version as of now

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Sync with upstream
        run: |
          git remote add upstream https://github.com/nvim-lua/kickstart.nvim.git
          git fetch upstream
          git checkout master
          git merge upstream/master --no-commit

      - name: Check for conflicts
        id: check_conflicts
        run: |
          if git diff --name-only --diff-filter=U | grep . > /dev/null; then
            echo "has_conflicts=true" >> $GITHUB_OUTPUT
          else
            echo "has_conflicts=false" >> $GITHUB_OUTPUT
          fi

      - name: Push changes if no conflicts
        if: steps.check_conflicts.outputs.has_conflicts == 'false'
        run: |
          git commit -m "Merge upstream changes"
          git push origin master

      - name: Create Pull Request if conflicts
        if: steps.check_conflicts.outputs.has_conflicts == 'true'
        uses: peter-evans/create-pull-request@v5  # Updated to v5
        with:
          branch: upstream-sync
          title: 'Resolve conflicts with upstream'
          body: 'This PR was created to resolve conflicts with the upstream repository. Please resolve the conflicts manually.'
          base: master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
